{"name": "test_login_falhou", "status": "passed", "steps": [{"name": "Abrir a tela de login", "status": "passed", "start": 1755724032023, "stop": 1755724032024}, {"name": "Preencher usuário e senha incorretos", "status": "passed", "start": 1755724032024, "stop": 1755724032024}, {"name": "Clicar no botão de login", "status": "passed", "start": 1755724032024, "stop": 1755724032024}, {"name": "Validar mensagem de erro", "status": "passed", "attachments": [{"name": "Erro", "source": "7b511482-83f4-4465-b3e8-039366bc57d2-attachment.txt", "type": "text/plain"}], "start": 1755724032024, "stop": 1755724032025}], "attachments": [{"name": "stdout", "source": "61624351-9416-4e60-9d79-1b8e9fb417a9-attachment.txt", "type": "text/plain"}], "start": 1755724032023, "stop": 1755724032026, "uuid": "52c47381-7662-40e7-abd1-f80a3bc2980e", "historyId": "7ad02c982fd228e2fb49f66a4359d1fa", "testCaseId": "7ad02c982fd228e2fb49f66a4359d1fa", "fullName": "tests.test_login#test_login_falhou", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Funcionalidade de Login"}, {"name": "story", "value": "Falha no login com senha incorreta"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-9U5D9IN"}, {"name": "thread", "value": "11228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}