{"name": "test_login_falhou", "status": "failed", "statusDetails": {"message": "AssertionError: Senha incorreta\nassert 'errado' == '1234'\n  - 1234\n  + errado", "trace": "@allure.feature(\"Funcionalidade de Login\")\n    @allure.story(\"Falha no login com senha incorreta\")\n    @allure.severity(allure.severity_level.NORMAL)\n    def test_login_falhou():\n        usuario = \"admin\"\n        senha = \"errado\"\n    \n        with allure.step(\"Abrir a tela de login\"):\n            print(\"Tela de login aberta\")\n    \n        with allure.step(\"Preencher usuário e senha incorretos\"):\n            print(f\"Usuário: {usuario}, Senha: {senha}\")\n    \n        with allure.step(\"Clicar no botão de login\"):\n            print(\"Clique no botão de login\")\n    \n        with allure.step(\"Validar mensagem de erro\"):\n>           assert senha == \"1234\", \"Senha incorreta\"\nE           AssertionError: Senha incorreta\nE           assert 'errado' == '1234'\nE             - 1234\nE             + errado\n\ntests\\test_login.py:43: AssertionError"}, "steps": [{"name": "Abrir a tela de login", "status": "passed", "start": 1755723786998, "stop": 1755723786999}, {"name": "Preencher usuário e senha incorretos", "status": "passed", "start": 1755723786999, "stop": 1755723786999}, {"name": "Clicar no botão de login", "status": "passed", "start": 1755723786999, "stop": 1755723786999}, {"name": "Validar mensagem de erro", "status": "failed", "statusDetails": {"message": "AssertionError: Senha incorreta\nassert 'errado' == '1234'\n  - 1234\n  + errado\n", "trace": "  File \"D:\\Estrutura de Automações\\Python\\Python_Automacao\\tests\\test_login.py\", line 43, in test_login_falhou\n    assert senha == \"1234\", \"Senha incorreta\"\n"}, "start": 1755723786999, "stop": 1755723787000}], "attachments": [{"name": "stdout", "source": "4cf2a6ff-2946-4997-8db6-db55ed1e0966-attachment.txt", "type": "text/plain"}], "start": 1755723786998, "stop": 1755723787003, "uuid": "79e024f6-772d-455e-8a23-bee971d3de72", "historyId": "7ad02c982fd228e2fb49f66a4359d1fa", "testCaseId": "7ad02c982fd228e2fb49f66a4359d1fa", "fullName": "tests.test_login#test_login_falhou", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Funcionalidade de Login"}, {"name": "story", "value": "Falha no login com senha incorreta"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-9U5D9IN"}, {"name": "thread", "value": "5916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}